apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blue-green
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3100
    protocol: TCP
    name: http
  selector:
    app: frontend
    version: blue
